### ISSUE TITLE
Somes minor issues I had on Ubuntu 16.04 server

### ISSUE THREAD

**Issue by tibidi** [MikeFultonDev/samples-old#6]
Very usefully to quickly setup a z/Os 😄 

I first had to replace double [[ and ]] with single [ and ] for `bringupSystem.sh`. Maybe an envvar I missed to define.

```
./bringupSystem.sh: 3: ./bringupSystem.sh: [[: not found
```

Then I added to the last command `. ~/.profile;`
```
echo "Let TSTRADM receive/apply PTFs"
${SSH} "${ZOS_USER}@${ZOS_HOST}" ". ~/.profile;. racfpermit facility 'gim.*'"
if [ $? -gt 0 ]; then
        echo "...failed"
        exit 16
fi
```

Error the error:
```
Let TSTRADM receive/apply PTFs
bash: racfpermit: command not found

```

**Comment by mikefultoniphone** [comment]
Thanks for the feedback! Sorry I took so long to respond - I hadn’t seen this.
